{% set name = "parameterized" %}
{% set version = "0.7.1" %}
{% set sha256 = "6a94dbea30c6abde99fd4c2f2042c1bf7f980e48908bf92ead62394f93cf57ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - parameterized

about:
  home: https://github.com/wolever/parameterized
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Parameterized testing with any Python test framework'
  description: |
    Parameterized testing in Python sucks.
    parameterized fixes that. For everything. Parameterized testing for nose,
    parameterized testing for py.test, parameterized testing for unittest.
  dev_url: https://github.com/wolever/parameterized

extra:
  recipe-maintainers:
    - chohner
