{% set name = "parameterized" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fc905272cefa4f364c1a3429cbbe9c0f98b793988efb5bf90aac80f08db09b1

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - parameterized
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/wolever/parameterized
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parameterized testing with any Python test framework
  description: |
    Parameterized testing in Python sucks.
    parameterized fixes that. For everything. Parameterized testing for nose,
    parameterized testing for py.test, parameterized testing for unittest.
  dev_url: https://github.com/wolever/parameterized
  doc_url: https://github.com/wolever/parameterized

extra:
  recipe-maintainers:
    - chohner
