travis:
  secure:
    BINSTAR_TOKEN: JL/+rQ7vnxkLi5ja1yMGX+l+R+oYvb6kkwqFUjPYWKtKxCUgkuBS807f6BYG3wIii+cDFrX3iJN0SYBRZMAmQ67ydFYRv9FEVEAbLwOVWeE0FxsgJk03JZneCCfoFdEeuUc7PJSAA8TXmTbczRSYEXHGlJS41KQfjLKpRGKf9ZGm0dc7T5uvUhAVG80C859lMCsDwbOdmBT3homLxREZIuykamgmlkSfvGje/TqcA7nBdysBLwCF7jQPmSaZ2rOUcB8+ZFd25QmujMMsydtb9hgxYN9nhGV8Gv3jPSHvUsSo5A3wsmXN3I74fzt/8R+keZ6kbWnYOgcc1KlCT6xomO3csB3OQi5XxM8m1fhXghhgg5ZaEk1WgN9vc8bFAGbuNqV0Z2b10dLBCODfVI83czAp522NlZ40fYmw1LenFzeO5C4MALAMywCL3A16CJw0nB48ArkIClPWGhJHevaCwc5aN/8co/+zfXG4EFOQVFPBSQ8d5N5thCpf2SJWecXksiUj6W59Qsek5mXkmLucGwCp4JGv2RjpkxtAYp929f+sEp8H3E9Hhsjlgudcf1ewDZ6XydNYWLwhzPgjQrzZmjzMCB1vG3u1tHQL4qKj9eev89wJcHXm5STUFXSEzGrcXPP5/5q8DC9h10RvC90qOyOd0Axx2QK86ctY597jhSI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
