travis:
  secure:
    BINSTAR_TOKEN: V6OOl47VKqVZ6PHZeYFbZmoRTbHVO/W5R+DTFwbCnIv3xIe0gy9OOMDBwDW7sTdrQH8ju7BT4kN+YwF9KS2wtwkP7X+BxH8DF0oVyMadJweMRKy9zQhglcnn+BWrEt0FvIh6Hbm0gQGg8gMe34tvx47veEm+tjFciLguFMzGI7WugzbgVe1DhQehGC40aUL+7Wm4kZLvJzVuI+uPv/onXTg5DHQ88r71xKMIxlkAuO5m6bJhStUl+tyZ3s3wzGaMMDCwOczBBd/wf6qI67WRXUEksb8ebteYnQXgyiDJrYvjxips51AstHjw6bEqhz0RnXMNHiMkPVvKFWKQruJXqHg/aPWqzrL4gnnyfD3Zlmhdoa3TgKKkKuRkmDHjcS2hh+wHJR2s/k1Hu/oNFYT2a+yxAZuRxyPgfh90Tx9p0g8gswZZO7tT1lInH3+lxQvYh7tKLqvxsN26vrHdwnZICSclqmgEWEtg7DH0bUBSQn5ZaNcwPDWMK1cotopXpqQafJP2ZaE9bA4U18wlhzjUgvESwgvuel7EBDnwVlWjR5BfZvYHPhbakDDs/f3OmtjzWfFbqEY/JlNYln4E7l8EU9ldhJ2j54G14EYI68pp8ayBKgPUKYx0NlGElEQFtEyUjV5zgp9W59txrmvHvXpVWgcaAP0tKHTNtM43wTIyJdc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
